name: ci

on:
  workflow_dispatch:
  push:

jobs:
  ci:
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          install_only: true

      - name: CI
        run: |
          make

      - name: Debug failure
        if: failure()
        run: |
          kubectl get all,ing,cm -A
          kubectl get events --sort-by='.metadata.creationTimestamp' -A
